server:
  port: 8082




spring:

  jpa:
    hibernate.ddl-auto: update
    database-platform: org.hibernate.dialect.MySQLDialect

  datasource:
      url: jdbc:mysql://localhost:3306/online_shop?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
      username: shop-admin
      password: stagiar


